services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3069:3000"
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.<unique-name>.rule=Host(`yopem.com`)
      - traefik.http.routers.<unique-name>.entrypoints=websecure
      - traefik.http.routers.<unique-name>.tls.certResolver=letsencrypt
      - traefik.http.services.<unique-name>.loadbalancer.server.port=3000
networks:
  dokploy-network:
    external: true
